[[OpenPolicyAgent]]
arch = "aarch64"
git-tree-sha1 = "7fca14234a1038187da90a85f8393e9201b20dd0"
os = "macos"

    [[OpenPolicyAgent.download]]
    sha256 = "5d53992dee25feabfd97f1c5c3cc8a0f6eb970650896dc82747cd83bd95c1d18"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.aarch64-apple-darwin.tar.gz"
[[OpenPolicyAgent]]
arch = "aarch64"
git-tree-sha1 = "734bd112a3eed127aba2ca77405ae4ce0fa4a490"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "07c63e96ba5074e20536c6f53e17ebb42cbc7cdbac8e3fb7eda6b69667ac3249"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.aarch64-linux-gnu.tar.gz"
[[OpenPolicyAgent]]
arch = "aarch64"
git-tree-sha1 = "734bd112a3eed127aba2ca77405ae4ce0fa4a490"
libc = "musl"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "07c63e96ba5074e20536c6f53e17ebb42cbc7cdbac8e3fb7eda6b69667ac3249"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.aarch64-linux-musl.tar.gz"
[[OpenPolicyAgent]]
arch = "aarch64"
git-tree-sha1 = "9c9c7454837bf72994872ef71d0367bc1394027f"
os = "freebsd"

    [[OpenPolicyAgent.download]]
    sha256 = "0697d590d2131c7b7563d6e74866b78f2ead62577d1f28ee9b5339cfdf00d780"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.aarch64-unknown-freebsd.tar.gz"
[[OpenPolicyAgent]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "55d7c8e2945c741ddd0565b44c72c74bc6edaf3d"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "4f9847d4dc9e993fb04594b86fa6cfc74943abdfbb8f716f0ffb48ee9250ce7d"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.armv6l-linux-gnueabihf.tar.gz"
[[OpenPolicyAgent]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "55d7c8e2945c741ddd0565b44c72c74bc6edaf3d"
libc = "musl"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "4f9847d4dc9e993fb04594b86fa6cfc74943abdfbb8f716f0ffb48ee9250ce7d"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.armv6l-linux-musleabihf.tar.gz"
[[OpenPolicyAgent]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "835bff9f26db6e213b6c8073894a18673aa173d0"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "3d2a5c2dd8b374c5e56fa286106f01fc4077f8b233399b6e7818aea9e773ad66"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.armv7l-linux-gnueabihf.tar.gz"
[[OpenPolicyAgent]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "835bff9f26db6e213b6c8073894a18673aa173d0"
libc = "musl"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "3d2a5c2dd8b374c5e56fa286106f01fc4077f8b233399b6e7818aea9e773ad66"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.armv7l-linux-musleabihf.tar.gz"
[[OpenPolicyAgent]]
arch = "i686"
git-tree-sha1 = "3c81bfd44cde998e779a21e516f2928a40ce2ba7"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "a6a661b2726b9aecb8c50b45624f3e6824a3fa606f1afd9ff53ffa1f16a74d8e"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.i686-linux-gnu.tar.gz"
[[OpenPolicyAgent]]
arch = "i686"
git-tree-sha1 = "3c81bfd44cde998e779a21e516f2928a40ce2ba7"
libc = "musl"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "a6a661b2726b9aecb8c50b45624f3e6824a3fa606f1afd9ff53ffa1f16a74d8e"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.i686-linux-musl.tar.gz"
[[OpenPolicyAgent]]
arch = "i686"
git-tree-sha1 = "42b9ebf9867238da7935442d7fd48b37133e1907"
os = "windows"

    [[OpenPolicyAgent.download]]
    sha256 = "651b4ca229148d1831ff1f1d22d0b87852f978eec68b081520ecab3d545a4912"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.i686-w64-mingw32.tar.gz"
[[OpenPolicyAgent]]
arch = "powerpc64le"
git-tree-sha1 = "29c730c4e3fef7dad560c8046288accb9d8deed3"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "659c1079023951abcea6f3b46ecd1fdf80c5ab4a1ea659644bfb50fafe1ca34b"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.powerpc64le-linux-gnu.tar.gz"
[[OpenPolicyAgent]]
arch = "riscv64"
git-tree-sha1 = "25482ae0cd2d976b18c0837033d84422d4ff1d74"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "19ce1e9c9d03344c38b930be5096475ff308a44ddd281f05c2b5ebe4fc71b223"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.riscv64-linux-gnu.tar.gz"
[[OpenPolicyAgent]]
arch = "x86_64"
git-tree-sha1 = "f78103553447d38f324d67cd902e388ab7181792"
os = "macos"

    [[OpenPolicyAgent.download]]
    sha256 = "4bbc81825339a986437659651d8de80d1bd590f3abb6e1b4969242c5ec2532a9"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.x86_64-apple-darwin.tar.gz"
[[OpenPolicyAgent]]
arch = "x86_64"
git-tree-sha1 = "a2e44f9cd9a3aa7c94579fb343d6c6ca532afb02"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "23023399cfa211412e195ff1761ae607546176a6bb1eed558587e03ad8a31ffc"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.x86_64-linux-gnu.tar.gz"
[[OpenPolicyAgent]]
arch = "x86_64"
git-tree-sha1 = "a2e44f9cd9a3aa7c94579fb343d6c6ca532afb02"
libc = "musl"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "23023399cfa211412e195ff1761ae607546176a6bb1eed558587e03ad8a31ffc"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.x86_64-linux-musl.tar.gz"
[[OpenPolicyAgent]]
arch = "x86_64"
git-tree-sha1 = "0a25f7b01edd9d97fef2112792759fee1ab7b49c"
os = "freebsd"

    [[OpenPolicyAgent.download]]
    sha256 = "d437d46b5b5198f5c9339a719e44af0c854d0e64a5e37ef0dffff35613fc3cc9"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.x86_64-unknown-freebsd.tar.gz"
[[OpenPolicyAgent]]
arch = "x86_64"
git-tree-sha1 = "294e68ae5ae3024e0bd696d589c2877c033a1f0e"
os = "windows"

    [[OpenPolicyAgent.download]]
    sha256 = "bccf6f77494414e731d00d0483a697bb3af8b83124dfa2739cc25e671cef644e"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v1.5.1+0/OpenPolicyAgent.v1.5.1.x86_64-w64-mingw32.tar.gz"
