[[OpenPolicyAgent]]
arch = "aarch64"
git-tree-sha1 = "c71bca777e76e588b4724105584ec7a6629b5bea"
os = "macos"

    [[OpenPolicyAgent.download]]
    sha256 = "5efd73c6ad555f000c1d8f2f196c3ddc3de7d44f31a36d4b46cdc478fed6aacf"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.aarch64-apple-darwin.tar.gz"
[[OpenPolicyAgent]]
arch = "aarch64"
git-tree-sha1 = "d9779fd95fb20473bda16dfb1963c6910a143adb"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "c1b48bdc80a2187e6d2cc5bf101041bb00cbb306d558e040171ea93d3c3fd833"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.aarch64-linux-gnu.tar.gz"
[[OpenPolicyAgent]]
arch = "aarch64"
git-tree-sha1 = "d9779fd95fb20473bda16dfb1963c6910a143adb"
libc = "musl"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "c1b48bdc80a2187e6d2cc5bf101041bb00cbb306d558e040171ea93d3c3fd833"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.aarch64-linux-musl.tar.gz"
[[OpenPolicyAgent]]
arch = "aarch64"
git-tree-sha1 = "6ae682c60055b57f77662c522be1d92398e65d75"
os = "freebsd"

    [[OpenPolicyAgent.download]]
    sha256 = "899a29f43dd9b917490f40ff35dfc4a9e308d2d2c25d4de1805eeada2ecea723"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.aarch64-unknown-freebsd.tar.gz"
[[OpenPolicyAgent]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8a97769fbadb82baa072398a4bdaccac3ebf4639"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "4d2955fc0d663bb002251a41d98328add7a4171e278ef06728f3a0a6e6254f36"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.armv6l-linux-gnueabihf.tar.gz"
[[OpenPolicyAgent]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8a97769fbadb82baa072398a4bdaccac3ebf4639"
libc = "musl"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "4d2955fc0d663bb002251a41d98328add7a4171e278ef06728f3a0a6e6254f36"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.armv6l-linux-musleabihf.tar.gz"
[[OpenPolicyAgent]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2269c1758a179a79b107754edf204161a9c359f9"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "1c711e3ce43f8fd8e8d282a52d89d1100cdf03f819244c516715c4f275dcd797"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.armv7l-linux-gnueabihf.tar.gz"
[[OpenPolicyAgent]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2269c1758a179a79b107754edf204161a9c359f9"
libc = "musl"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "1c711e3ce43f8fd8e8d282a52d89d1100cdf03f819244c516715c4f275dcd797"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.armv7l-linux-musleabihf.tar.gz"
[[OpenPolicyAgent]]
arch = "i686"
git-tree-sha1 = "9885a2279e1e0038c154bc74881df36062537698"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "27a17971ae7a24ee9093ec4dd16d086a6693c480893bf3dd334ed5bd8712d713"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.i686-linux-gnu.tar.gz"
[[OpenPolicyAgent]]
arch = "i686"
git-tree-sha1 = "9885a2279e1e0038c154bc74881df36062537698"
libc = "musl"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "27a17971ae7a24ee9093ec4dd16d086a6693c480893bf3dd334ed5bd8712d713"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.i686-linux-musl.tar.gz"
[[OpenPolicyAgent]]
arch = "i686"
git-tree-sha1 = "c339b423ed7549e36062731964a86b0d76c10bfb"
os = "windows"

    [[OpenPolicyAgent.download]]
    sha256 = "9f40b4b16deaf8ace6895594013df3e5cacb8cfdecfee9b3b70547a9dea8f69c"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.i686-w64-mingw32.tar.gz"
[[OpenPolicyAgent]]
arch = "powerpc64le"
git-tree-sha1 = "a87f465ebef2c762b73dfc22d467475384a1451b"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "58185d320f2fa1a84d773c6ab506554c9e14f7cdaaaaf05e5f1e5b21e7fa2593"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.powerpc64le-linux-gnu.tar.gz"
[[OpenPolicyAgent]]
arch = "x86_64"
git-tree-sha1 = "295960d44f1d6896ec2dff005320c37d7ce5386a"
os = "macos"

    [[OpenPolicyAgent.download]]
    sha256 = "b3769193eb4deb47a26feb86f5ecc815348d8ccab0a5b155c6462f53c6519d69"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.x86_64-apple-darwin.tar.gz"
[[OpenPolicyAgent]]
arch = "x86_64"
git-tree-sha1 = "494dd898a049e80e840e246f03e4a94d7de6cdef"
libc = "glibc"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "ea7952ad72b9e07932bd741f9850c430046481e3c5424a7cf18190d062bc867a"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.x86_64-linux-gnu.tar.gz"
[[OpenPolicyAgent]]
arch = "x86_64"
git-tree-sha1 = "494dd898a049e80e840e246f03e4a94d7de6cdef"
libc = "musl"
os = "linux"

    [[OpenPolicyAgent.download]]
    sha256 = "ea7952ad72b9e07932bd741f9850c430046481e3c5424a7cf18190d062bc867a"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.x86_64-linux-musl.tar.gz"
[[OpenPolicyAgent]]
arch = "x86_64"
git-tree-sha1 = "b6f1b4af7df2040e3a8b57f5c99ca7b8dba9795a"
os = "freebsd"

    [[OpenPolicyAgent.download]]
    sha256 = "76d2d89a793b121ac387d1cecc9ad26506214c4ae2ce98298bcec48176ac88b8"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.x86_64-unknown-freebsd.tar.gz"
[[OpenPolicyAgent]]
arch = "x86_64"
git-tree-sha1 = "287271983f3f79d724bbdbe0d1e60779f473c868"
os = "windows"

    [[OpenPolicyAgent.download]]
    sha256 = "032f6bd8e8ee21254124020ebd5673bf94fcd61e0fa6f70d23854480e1b28172"
    url = "https://github.com/JuliaBinaryWrappers/OpenPolicyAgent_jll.jl/releases/download/OpenPolicyAgent-v0.69.0+0/OpenPolicyAgent.v0.69.0.x86_64-w64-mingw32.tar.gz"
